version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: "pub"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: '04:00'
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/android/app"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
